### ISSUE TITLE
新規登録・ログイン前のカートへ入れるボタン

### ISSUE THREAD

**Issue by ekusuy0** [webcamp-solt/Naganocake#12]
**public/items/show.html.erbのカートボタンの表示をどうするか**

1. 表示しない
2. リンクで登録ページに飛ばす

どうするか考えよう

**Comment by m9795** [comment]
1. 表示しない場合
→ **カートへ追加するには　新規登録　または　ログインが必要です**などを表示
2. リンクで飛ばす場合
→ ログイン画面へ遷移

どうしよう・・？

**Comment by m9795** [comment]
はまちゃんが修正してくれました。
